data:extend({
  { type = "custom-input", name = "bpt-import-string", key_sequence = "ALT + I", order = "a" },
  {
    type = "custom-input",
    name = "bpt-swap-wire-colors",
    key_sequence = "SHIFT + C",
    order = "aa",
  },
  {
    type = "custom-input",
    name = "bpt-set-tiles",
    key_sequence = "SHIFT + T",
    order = "ab",
  },
  {
    type = "custom-input",
    name = "bpt-quick-grid",
    key_sequence = "SHIFT + G",
    order = "ac",
  },
  {
    type = "custom-input",
    name = "bpt-configure",
    key_sequence = "SHIFT + B",
    order = "ad",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-grid-up",
    key_sequence = "SHIFT + UP",
    order = "ba",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-grid-down",
    key_sequence = "SHIFT + DOWN",
    order = "bb",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-grid-left",
    key_sequence = "SHIFT + LEFT",
    order = "bc",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-grid-right",
    key_sequence = "SHIFT + RIGHT",
    order = "bd",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-up",
    key_sequence = "CONTROL + SHIFT + UP",
    order = "ca",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-down",
    key_sequence = "CONTROL + SHIFT + DOWN",
    order = "cb",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-left",
    key_sequence = "CONTROL + SHIFT + LEFT",
    order = "cc",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-right",
    key_sequence = "CONTROL + SHIFT + RIGHT",
    order = "cd",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-book-up",
    key_sequence = "",
    order = "da",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-book-down",
    key_sequence = "",
    order = "db",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-book-left",
    key_sequence = "",
    order = "dc",
  },
  {
    type = "custom-input",
    name = "bpt-nudge-absolute-grid-book-right",
    key_sequence = "",
    order = "dd",
  },
  {
    type = "custom-input",
    name = "bpt-linked-confirm-gui",
    key_sequence = "",
    linked_game_control = "confirm-gui",
  },
  {
    type = "custom-input",
    name = "bpt-linked-clear-cursor",
    key_sequence = "",
    linked_game_control = "clear-cursor",
  },
})
